### ISSUE TITLE
question: Pause Menu

### ISSUE THREAD

**Issue by panoschagias** [jadijadi/riverraidrust#31]
I was wondering if it is possible to create a pause menu with crossterm.
The idea came from those dialog boxes we see in curses apps, who seem like popup illusions, but I don't know if crossterm has this functionality. 
Any ideas?

**Comment by jadijadi** [comment]
normally not. crossterm is very "basic" but as you can see in the recent PR by kohoolatesen, it is possible to create some kind of box and such, manually.
