### ISSUE TITLE
river gets blocked some times

### ISSUE THREAD

**Issue by Siavoosh** [jadijadi/riverraidrust#35]
<img width="999" alt="Screenshot 1402-12-22 at 6 24 48 in the evening" src="https://github.com/jadijadi/riverraidrust/assets/38927495/7543517e-329b-4fb1-83e1-8a3de7d5bf98">

**Comment by panoschagias** [comment]
This issue already exists in #29.

**Comment by Siavoosh** [comment]
i see. thanks for explanation.
